// render_sphere.wgsl — Phase 4 Near-LOD icosphere render pass.
//
// Renders instanced low-poly icospheres (20 tris, 12 verts, subdivided once).
// Each NeuronInstance provides position, glow, color.
//
// Vertex shader: world_pos = instance_pos + sphere_vertex * radius * (0.5 + glow)
// Fragment: Blinn-Phong + emissive glow tint.
// Blended: alpha-premultiplied over the existing depth (LoadOp::Load).

struct NearUniforms {
    mvp: mat4x4<f32>,
    camera_pos: vec3<f32>,
    sphere_radius: f32,   // base radius in world units
    lod_alpha: f32,       // crossfade alpha [0..1], 1 = fully visible
    _pad0: f32,
    _pad1: f32,
    _pad2: f32,
}

struct NeuronInstance {
    pos: vec3<f32>,
    glow: f32,
    color: vec3<f32>,
    _pad: f32,
}

@group(0) @binding(0) var<uniform> u: NearUniforms;
@group(0) @binding(1) var<storage, read> neuron_instances: array<NeuronInstance>;

struct VOut {
    @builtin(position) clip_pos: vec4<f32>,
    @location(0) world_pos: vec3<f32>,
    @location(1) normal: vec3<f32>,
    @location(2) color: vec3<f32>,
    @location(3) glow: f32,
}

// Sphere vertex and index data embedded as constants (icosphere level-1, 20 tris).
// Generated by the CPU at startup and accessed via vertex/index buffers;
// this shader reads them as per-vertex attributes in input layout slot 0/1.

// Vertex layout: position (float32x3) + normal (float32x3) = 24 bytes/vertex.
// The geometry is the unit icosphere; the VS scales to (radius * (0.5 + glow)).
// Normals equal positions on a unit sphere.

@vertex
fn vs_main(
    @location(0) local_pos: vec3<f32>,    // unit sphere vertex
    @location(1) local_normal: vec3<f32>, // == local_pos for unit sphere
    @builtin(instance_index) inst_idx: u32,
) -> VOut {
    let inst = neuron_instances[inst_idx];
    let radius = u.sphere_radius * (0.5 + inst.glow);
    let world = inst.pos + local_pos * radius;

    var out: VOut;
    out.clip_pos  = u.mvp * vec4(world, 1.0);
    out.world_pos = world;
    out.normal    = local_normal;  // world-space normal = local normal (no rotation)
    out.color     = inst.color;
    out.glow      = inst.glow;
    return out;
}

@fragment
fn fs_main(in: VOut) -> @location(0) vec4<f32> {
    // Simple diffuse lighting + emissive glow.
    let light_dir = normalize(u.camera_pos - in.world_pos);
    let diff = max(dot(normalize(in.normal), light_dir), 0.0);

    let base_col = in.color * (0.3 + 0.7 * diff);
    let emissive  = in.color * in.glow * 1.5;
    let final_col = base_col + emissive;

    // Alpha blends nicely in crossfade range via lod_alpha.
    let alpha = u.lod_alpha * (0.85 + in.glow * 0.15);
    return vec4(final_col * alpha, alpha);
}
